language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - python2 bootstrap.py
  - mv openprocurement/auction/esco/tests/data/travis_worker_esco.yaml openprocurement/auction/esco/tests/data/auction_worker_esco.yaml
install:
  - bin/buildout -N
  - curl -X PUT 0.0.0.0:5984/auctions
script:
  - bin/pytest openprocurement/auction/esco/tests -v
